name: Renovate CLI validation

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Validate Renovate config
        run: npx --yes --package renovate renovate-config-validator renovate.json

      - name: Renovate dry-run
        env:
          RENOVATE_TOKEN: ${{ github.token }}
          LOG_LEVEL: debug
        run: npx --yes --package renovate renovate --dry-run=full matsudamper/FolderViewer
